import  qrcode
print ("<<<<<<<<<<<<<<<<<<<<AlphaGenQR 1.1ab by GatoVerde95 (1.1.8ab build 1856201)>>>>>>>>>>>>>>>>>>>>")
print ("Hola!!!!!! :) Bienvenido al Generador de Codigos QR")
print (">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
print (">>>>>>>>>>A CONTINUACION<<<<<<<<<<<<<<")
print ("- Ingrese/Escriba/Teclee el contenido que tendra su codigo QR (Pueden ser Links, Texto(Limitado a 150 letras), Mensaje, Correos, PINs o Contraseñas (Inseguro):")
img=qrcode.make(input())
img.save("qr_generated.png")
print ("Hecho!, su codigo QR se ha generado")
time.sleep(3)
print ("Cerrando AlphaGenQR.......")
time.sleep(3)
print ("Apagando Librerias.......")
time.sleep(3)
print ("Cerrando PowerShell.......")
time.sleep(3)
print ("Cerrando cmd.exe.......")
time.sleep(3)
print ("Cerrando qrcode.pip.......")
time.sleep(3)
print ("Cerrando Python 3.13.......")
time.sleep(3)
print ("Cerrando PythonPrint.......")
time.sleep(3)
print ("Cerrando PythonIMG.......")
time.sleep(3)
print ("Cerrando OpenCV.......")
time.sleep(3)
print ("Cerrando PyImput.......")
time.sleep(3)
exit()
